analyzer:
  errors:
    always_use_package_imports: ignore
    avoid_dynamic_calls: ignore
    cascade_invocations: ignore
    inference_failure_on_function_invocation: ignore
    invalid_annotation_target: ignore
    noop_primitive_operations: ignore
    require_trailing_commas: ignore
    use_super_parameters: ignore

  exclude:
  - '**/*.freezed.dart'
  - '**/*.g.dart'
  - '**/*.pb.dart'
  - '**/*.pbenum.dart'
  - '**/*.pbgrpc.dart'
  - '**/*.pbjson.dart'
  - '**/*.pbserver.dart'
  - '**/intl_messages*.dart'
  - 'lib/**.config.dart'
  
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false